name: ğŸ“• Update Posts
on:
  push:
    branches: [ master ]
jobs:
  update:
    name: ğŸ“• Update Posts
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout â¬‡ï¸
        uses: actions/checkout@v2

      - name: â” Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Node test
        run: node -v